/**
 * RankHub Centralized Exam Data Store
 * Provides rich data for all competitive exam categories:
 * SSC, Banking, Railway, UPSC, State PSC, Police, Defence, Teaching, Medical, Engineering, Law, Insurance, MBA, CUET, State Government Jobs.
 */

export const CATEGORIES = [
  'All',
  'Popular',
  'Banking',
  'SSC',
  'Railway',
  'UPSC',
  'State PSC',
  'Police',
  'Defence',
  'Teaching',
  'Medical',
  'Engineering',
  'Law',
  'Insurance',
  'MBA',
  'CUET',
  'State Government Jobs'
];

export const EXAMS_DATA = [
  // ==================== SSC EXAMS ====================
  {
    id: 'ssc-cgl',
    name: 'SSC CGL',
    fullTitle: 'Staff Selection Commission - Combined Graduate Level',
    category: 'SSC',
    description: 'Premier recruitment exam for Group B & C Officer posts in Central Ministries, Income Tax, Excise, & Audit departments.',
    logoText: 'SSC',
    logoBg: '#EFF6FF',
    logoColor: '#2563EB',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '120+ Mock Tests',
    questionCount: '5000+ Questions',
    pyqYears: '15 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Notification Active',
    tierInfo: 'Tier 1 (CBT) & Tier 2 (CBT + Skill Test)',
    eligibility: 'Bachelor Degree in any discipline from a recognized University',
    subjects: ['Quantitative Aptitude', 'Reasoning Ability', 'English Language', 'General Awareness', 'Computer Knowledge'],
    keywords: 'ssc cgl staff selection combined graduate level income tax excise audit tier 1 tier 2 reasoning math english gk',
    mockTestsList: [
      { id: 'cgl-m1', title: 'SSC CGL Tier-1 Full Mock Test 01', duration: '60 Mins', questions: 100, marks: 200, status: 'Free' },
      { id: 'cgl-m2', title: 'SSC CGL Tier-1 Full Mock Test 02', duration: '60 Mins', questions: 100, marks: 200, status: 'Free' },
      { id: 'cgl-m3', title: 'SSC CGL Tier-1 Quant Special Test', duration: '30 Mins', questions: 50, marks: 100, status: 'Pro' },
      { id: 'cgl-m4', title: 'SSC CGL Tier-1 Reasoning Mastery', duration: '30 Mins', questions: 50, marks: 100, status: 'Pro' },
      { id: 'cgl-m5', title: 'SSC CGL Tier-2 Paper 1 Full Mock', duration: '150 Mins', questions: 130, marks: 390, status: 'Pro' }
    ],
    practiceSets: [
      { id: 'cgl-p1', subject: 'Quantitative Aptitude', topic: 'Algebra & Geometry High-Yield', qCount: 25, duration: '20 Mins' },
      { id: 'cgl-p2', subject: 'Reasoning Ability', topic: 'Coding-Decoding & Syllogism', qCount: 25, duration: '15 Mins' },
      { id: 'cgl-p3', subject: 'English Language', topic: 'Error Spotting & Reading Comprehension', qCount: 25, duration: '15 Mins' },
      { id: 'cgl-p4', subject: 'General Awareness', topic: 'Indian Polity & Science MCQs', qCount: 25, duration: '10 Mins' }
    ],
    pyqList: [
      { id: 'cgl-pyq-2025', year: '2025', title: 'SSC CGL Tier-1 Official Paper 2025 (Shift 1)', duration: '60 Mins', questions: 100 },
      { id: 'cgl-pyq-2024', year: '2024', title: 'SSC CGL Tier-1 Official Paper 2024 (Shift 2)', duration: '60 Mins', questions: 100 },
      { id: 'cgl-pyq-2023', year: '2023', title: 'SSC CGL Tier-1 Official Paper 2023 (Shift 1)', duration: '60 Mins', questions: 100 },
      { id: 'cgl-pyq-2022', year: '2022', title: 'SSC CGL Tier-1 Official Paper 2022 (Shift 3)', duration: '60 Mins', questions: 100 }
    ],
    studyNotes: [
      { id: 'cgl-n1', title: 'Complete Mensuration & Geometry Formula Booklet', pages: '42 Pages', format: 'PDF' },
      { id: 'cgl-n2', title: '500 Most Frequently Asked Vocabularies & Idioms', pages: '28 Pages', format: 'PDF' },
      { id: 'cgl-n3', title: 'Indian Constitution & Articles Quick Revision', pages: '35 Pages', format: 'PDF' }
    ],
    currentAffairsList: [
      { id: 'ca-1', title: 'Monthly Current Affairs Digest - Last 12 Months', date: 'August 2026' },
      { id: 'ca-2', title: 'Government Schemes & Union Budget Summary', date: 'July 2026' }
    ]
  },
  {
    id: 'ssc-chsl',
    name: 'SSC CHSL',
    fullTitle: 'Staff Selection Commission - Combined Higher Secondary Level',
    category: 'SSC',
    description: 'Recruitment for Lower Division Clerk (LDC), Junior Secretariat Assistant (JSA), and Data Entry Operator (DEO).',
    logoText: 'SSC',
    logoBg: '#EFF6FF',
    logoColor: '#2563EB',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '100+ Mock Tests',
    questionCount: '4200+ Questions',
    pyqYears: '12 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Exam Cycle Active',
    tierInfo: 'Tier 1 & Tier 2 (Objective + Typing Test)',
    eligibility: '10+2 / Higher Secondary pass from recognized board',
    subjects: ['General Intelligence', 'English Language', 'Quantitative Aptitude', 'General Awareness'],
    keywords: 'ssc chsl 10+2 ldc deo jsa staff selection tier 1 tier 2 typing',
    mockTestsList: [
      { id: 'chsl-m1', title: 'SSC CHSL Tier-1 Full Mock Test 01', duration: '60 Mins', questions: 100, marks: 200, status: 'Free' },
      { id: 'chsl-m2', title: 'SSC CHSL Tier-1 Full Mock Test 02', duration: '60 Mins', questions: 100, marks: 200, status: 'Free' }
    ],
    practiceSets: [
      { id: 'chsl-p1', subject: 'Quantitative Aptitude', topic: 'Percentage & Profit Loss', qCount: 25, duration: '20 Mins' }
    ],
    pyqList: [
      { id: 'chsl-pyq-1', year: '2025', title: 'SSC CHSL Official Paper 2025', duration: '60 Mins', questions: 100 }
    ],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'ssc-mts',
    name: 'SSC MTS',
    fullTitle: 'Staff Selection Commission - Multi-Tasking Staff & Havaldar',
    category: 'SSC',
    description: 'Entry-level national examination for non-technical staff and Havaldar in Central Government offices.',
    logoText: 'MTS',
    logoBg: '#EFF6FF',
    logoColor: '#2563EB',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '85+ Mock Tests',
    questionCount: '3500+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Expected Oct 2026',
    tierInfo: 'Session 1 & Session 2 CBT',
    eligibility: '10th Class pass or equivalent',
    subjects: ['Numerical Ability', 'Reasoning Ability', 'General Awareness', 'English Language'],
    keywords: 'ssc mts havaldar 10th pass multi tasking staff math reasoning gk english',
    mockTestsList: [
      { id: 'mts-m1', title: 'SSC MTS Full Length Mock Test 01', duration: '90 Mins', questions: 90, marks: 270, status: 'Free' }
    ],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'ssc-gd',
    name: 'SSC GD Constable',
    fullTitle: 'Staff Selection Commission - General Duty Constable in CAPFs',
    category: 'SSC',
    description: 'Recruitment for Constables in BSF, CISF, CRPF, SSB, ITBP, AR, and SSF.',
    logoText: 'GD',
    logoBg: '#FEF2F2',
    logoColor: '#DC2626',
    statusBadgeText: 'UPCOMING',
    badgeClass: 'badge-upcoming',
    mockTestCount: '110+ Mock Tests',
    questionCount: '4500+ Questions',
    pyqYears: '8 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: true,
    expectedDate: 'Expected Dec 2026',
    tierInfo: 'Computer Based Test (CBE) & PST/PET',
    eligibility: 'Matriculation (10th) from a recognized Board',
    subjects: ['General Intelligence', 'General Knowledge', 'Elementary Mathematics', 'Hindi / English'],
    keywords: 'ssc gd constable capf bsf crpf cisf police 10th pass pet pst army',
    mockTestsList: [
      { id: 'gd-m1', title: 'SSC GD Constable Mock Test 01', duration: '60 Mins', questions: 80, marks: 160, status: 'Free' }
    ],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'ssc-cpo',
    name: 'SSC CPO',
    fullTitle: 'Staff Selection Commission - Sub Inspector in Delhi Police & CAPFs',
    category: 'SSC',
    description: 'Recruitment for Sub Inspector in Delhi Police, BSF, CRPF, CISF, ITBP, and SSB.',
    logoText: 'CPO',
    logoBg: '#EFF6FF',
    logoColor: '#2563EB',
    statusBadgeText: 'ACTIVE',
    badgeClass: 'badge-free',
    mockTestCount: '75+ Mock Tests',
    questionCount: '3000+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: false,
    isPopular: false,
    isUpcoming: false,
    expectedDate: 'Cycle Ongoing',
    tierInfo: 'Paper 1, PET/PST & Paper 2 (English)',
    eligibility: 'Bachelor degree in any stream',
    subjects: ['General Intelligence & Reasoning', 'General Knowledge', 'Quantitative Aptitude', 'English Comprehension'],
    keywords: 'ssc cpo sub inspector delhi police capf si pet english',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'ssc-je',
    name: 'SSC JE',
    fullTitle: 'Staff Selection Commission - Junior Engineer (Civil, Mech, Elec)',
    category: 'SSC',
    description: 'Technical recruitment exam for Junior Engineer posts in CPWD, MES, CWC, and Central Water Power Research Station.',
    logoText: 'JE',
    logoBg: '#EFF6FF',
    logoColor: '#2563EB',
    statusBadgeText: 'ACTIVE',
    badgeClass: 'badge-free',
    mockTestCount: '60+ Mock Tests',
    questionCount: '2800+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: false,
    isPopular: false,
    isUpcoming: false,
    expectedDate: 'Annual Exam',
    tierInfo: 'Paper 1 (CBT) & Paper 2 (Technical CBT)',
    eligibility: 'Degree or Diploma in Engineering (Civil/Mechanical/Electrical)',
    subjects: ['General Intelligence', 'General Awareness', 'Civil / Electrical / Mechanical Engineering'],
    keywords: 'ssc je junior engineer cpwd engineering civil mechanical electrical diploma',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'ssc-steno',
    name: 'SSC Stenographer',
    fullTitle: 'Staff Selection Commission - Stenographer Grade C & D',
    category: 'SSC',
    description: 'Recruitment for Stenographer Grade C and Grade D posts across Central Govt Ministries.',
    logoText: 'STENO',
    logoBg: '#EFF6FF',
    logoColor: '#2563EB',
    statusBadgeText: 'ACTIVE',
    badgeClass: 'badge-free',
    mockTestCount: '50+ Mock Tests',
    questionCount: '2200+ Questions',
    pyqYears: '8 Years PYQ',
    isFeatured: false,
    isPopular: false,
    isUpcoming: false,
    expectedDate: 'Notification Expected',
    tierInfo: 'CBT Examination & Skill Test in Stenography',
    eligibility: '10+2 Pass + Stenography speed requirement',
    subjects: ['General Intelligence & Reasoning', 'General Awareness', 'English Language & Comprehension'],
    keywords: 'ssc stenographer steno grade c grade d typing shorthand skill test',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },

  // ==================== BANKING EXAMS ====================
  {
    id: 'sbi-po',
    name: 'SBI PO',
    fullTitle: 'State Bank of India - Probationary Officer',
    category: 'Banking',
    description: 'Prestigious banking officer recruitment examination conducted by State Bank of India.',
    logoText: 'SBI',
    logoBg: '#EFF6FF',
    logoColor: '#0284C7',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '130+ Mock Tests',
    questionCount: '5200+ Questions',
    pyqYears: '14 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Expected Oct 2026',
    tierInfo: 'Prelims, Mains, Psychometric Test & Interview',
    eligibility: 'Bachelor degree in any discipline from a recognized University',
    subjects: ['Data Analysis & Interpretation', 'Reasoning & Computer Aptitude', 'English Language', 'General/Banking Awareness'],
    keywords: 'sbi po state bank officer prelims mains interview banking quant reasoning english ga',
    mockTestsList: [
      { id: 'sbipo-m1', title: 'SBI PO Prelims Full Length Mock 01', duration: '60 Mins', questions: 100, marks: 100, status: 'Free' },
      { id: 'sbipo-m2', title: 'SBI PO Prelims Full Length Mock 02', duration: '60 Mins', questions: 100, marks: 100, status: 'Free' },
      { id: 'sbipo-m3', title: 'SBI PO Mains Data Analysis Special', duration: '60 Mins', questions: 35, marks: 60, status: 'Pro' }
    ],
    practiceSets: [
      { id: 'sbipo-p1', subject: 'Quantitative Aptitude', topic: 'High-Level Data Interpretation (DI)', qCount: 20, duration: '20 Mins' },
      { id: 'sbipo-p2', subject: 'Reasoning Ability', topic: 'Seating Arrangement & Puzzles', qCount: 20, duration: '20 Mins' }
    ],
    pyqList: [
      { id: 'sbipo-pyq-1', year: '2025', title: 'SBI PO Prelims Official Memory Based Paper', duration: '60 Mins', questions: 100 },
      { id: 'sbipo-pyq-2', year: '2024', title: 'SBI PO Mains Official Memory Based Paper', duration: '180 Mins', questions: 155 }
    ],
    studyNotes: [
      { id: 'sbipo-n1', title: 'Complete Banking Awareness & Reserve Bank RBI Circulars 2026', pages: '50 Pages', format: 'PDF' }
    ],
    currentAffairsList: []
  },
  {
    id: 'sbi-clerk',
    name: 'SBI Clerk',
    fullTitle: 'State Bank of India - Junior Associate (Customer Support & Sales)',
    category: 'Banking',
    description: 'Mass recruitment for clerical staff in State Bank of India branches nationwide.',
    logoText: 'SBI',
    logoBg: '#EFF6FF',
    logoColor: '#0284C7',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '115+ Mock Tests',
    questionCount: '4800+ Questions',
    pyqYears: '12 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Exam Cycle Active',
    tierInfo: 'Prelims & Mains (No Interview)',
    eligibility: 'Graduation in any discipline',
    subjects: ['Numerical Ability', 'Reasoning Ability', 'English Language', 'General/Financial Awareness'],
    keywords: 'sbi clerk junior associate customer support state bank prelims mains',
    mockTestsList: [
      { id: 'sbiclerk-m1', title: 'SBI Clerk Prelims Mock Test 01', duration: '60 Mins', questions: 100, marks: 100, status: 'Free' }
    ],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'ibps-po',
    name: 'IBPS PO',
    fullTitle: 'Institute of Banking Personnel Selection - Probationary Officer',
    category: 'Banking',
    description: 'Officer cadre recruitment across 11 participating public sector banks in India.',
    logoText: 'IBPS',
    logoBg: '#F0FDF4',
    logoColor: '#16A34A',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '125+ Mock Tests',
    questionCount: '5000+ Questions',
    pyqYears: '13 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Exam Cycle Active',
    tierInfo: 'Prelims, Mains & Interview',
    eligibility: 'Graduation in any stream with computer literacy',
    subjects: ['Quantitative Aptitude', 'Reasoning', 'English', 'General & Banking Awareness'],
    keywords: 'ibps po banking probationary officer bank prelims mains computer',
    mockTestsList: [
      { id: 'ibpspo-m1', title: 'IBPS PO Prelims Full Mock 01', duration: '60 Mins', questions: 100, marks: 100, status: 'Free' }
    ],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'ibps-clerk',
    name: 'IBPS Clerk',
    fullTitle: 'Institute of Banking Personnel Selection - Clerical Cadre',
    category: 'Banking',
    description: 'State-wise clerical cadre recruitment in participating public sector banks.',
    logoText: 'IBPS',
    logoBg: '#F0FDF4',
    logoColor: '#16A34A',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '110+ Mock Tests',
    questionCount: '4500+ Questions',
    pyqYears: '11 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Annual Exam',
    tierInfo: 'Prelims & Mains (No Interview)',
    eligibility: 'Graduation degree & proficiency in local language',
    subjects: ['Reasoning', 'Numerical Ability', 'English', 'General/Financial Awareness'],
    keywords: 'ibps clerk bank clerical state language prelims mains',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'ibps-rrb-po',
    name: 'IBPS RRB Officer Scale 1',
    fullTitle: 'Institute of Banking Personnel Selection - Regional Rural Banks Officer',
    category: 'Banking',
    description: 'Officer Scale 1 recruitment for Regional Rural Banks across Indian states.',
    logoText: 'RRB',
    logoBg: '#F0FDF4',
    logoColor: '#16A34A',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '95+ Mock Tests',
    questionCount: '4000+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Annual Exam',
    tierInfo: 'Prelims, Mains & Interview',
    eligibility: 'Bachelor degree + Proficiency in regional language',
    subjects: ['Quantitative Aptitude', 'Reasoning Ability', 'Computer Knowledge', 'Financial Awareness', 'Hindi / English'],
    keywords: 'ibps rrb po regional rural bank scale 1 officer prelims mains',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'rbi-grade-b',
    name: 'RBI Grade B',
    fullTitle: 'Reserve Bank of India - Officers in Grade B (General / DEPR / DSIM)',
    category: 'Banking',
    description: 'Apex banking regulatory officer recruitment conducted by Reserve Bank of India.',
    logoText: 'RBI',
    logoBg: '#F0FDF4',
    logoColor: '#166534',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '55+ Mock Tests',
    questionCount: '2500+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: true,
    isPopular: false,
    isUpcoming: false,
    expectedDate: 'Notification Active',
    tierInfo: 'Phase 1, Phase 2 (ESI + FM) & Interview',
    eligibility: 'Graduation with min 60% marks (50% for SC/ST/PwBD)',
    subjects: ['General Awareness', 'Quantitative Aptitude', 'Reasoning', 'English Language', 'Economic & Social Issues', 'Finance & Management'],
    keywords: 'rbi grade b reserve bank officer phase 1 phase 2 esi fm economics finance',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },

  // ==================== RAILWAY EXAMS ====================
  {
    id: 'rrb-ntpc',
    name: 'RRB NTPC',
    fullTitle: 'Railway Recruitment Board - Non-Technical Popular Categories',
    category: 'Railway',
    description: 'Recruitment for Station Master, Goods Guard, Commercial Apprentice, and Senior Clerk in Indian Railways.',
    logoText: 'RRB',
    logoBg: '#FFF7ED',
    logoColor: '#EA580C',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '150+ Mock Tests',
    questionCount: '6000+ Questions',
    pyqYears: '12 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Expected Nov 2026',
    tierInfo: 'CBT 1, CBT 2 & Typing / CBAT',
    eligibility: '10+2 / Graduate depending on post category',
    subjects: ['General Awareness', 'Mathematics', 'General Intelligence & Reasoning'],
    keywords: 'rrb ntpc railway station master goods guard cbt 1 cbt 2 math reasoning gk',
    mockTestsList: [
      { id: 'ntpc-m1', title: 'RRB NTPC CBT-1 Full Length Mock 01', duration: '90 Mins', questions: 100, marks: 100, status: 'Free' },
      { id: 'ntpc-m2', title: 'RRB NTPC CBT-2 Full Length Mock 01', duration: '90 Mins', questions: 120, marks: 120, status: 'Pro' }
    ],
    practiceSets: [],
    pyqList: [
      { id: 'ntpc-pyq-1', year: '2024', title: 'RRB NTPC CBT 1 Official Memory Based Paper', duration: '90 Mins', questions: 100 }
    ],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'rrb-group-d',
    name: 'RRB Group D',
    fullTitle: 'Railway Recruitment Board - Level 1 Posts',
    category: 'Railway',
    description: 'Recruitment for Track Maintainer, Assistant Pointsman, and Level-1 posts in Indian Railways.',
    logoText: 'RRB',
    logoBg: '#FFF7ED',
    logoColor: '#EA580C',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '140+ Mock Tests',
    questionCount: '5500+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Expected Late 2026',
    tierInfo: 'CBT, Physical Efficiency Test (PET) & DV',
    eligibility: '10th pass or ITI from NCVT/SCVT',
    subjects: ['General Science', 'Mathematics', 'General Intelligence & Reasoning', 'Current Affairs'],
    keywords: 'rrb group d railway level 1 trackman pointsman science math reasoning',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'rrb-alp',
    name: 'RRB ALP',
    fullTitle: 'Railway Recruitment Board - Assistant Loco Pilot',
    category: 'Railway',
    description: 'Technical recruitment for Assistant Loco Pilot in Indian Railways trains & locomotives.',
    logoText: 'ALP',
    logoBg: '#FFF7ED',
    logoColor: '#EA580C',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '90+ Mock Tests',
    questionCount: '4000+ Questions',
    pyqYears: '8 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Cycle Active',
    tierInfo: 'CBT 1, CBT 2 (Part A & B) & CBAT (Psychometric)',
    eligibility: 'Matriculation + ITI / Diploma in Engineering',
    subjects: ['Mathematics', 'General Intelligence', 'Basic Science & Engineering', 'General Awareness', 'Technical Trade'],
    keywords: 'rrb alp assistant loco pilot railway locomotive cbt 1 cbt 2 trade iti diploma',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'rrb-technician',
    name: 'RRB Technician',
    fullTitle: 'Railway Recruitment Board - Technician Grade I & III',
    category: 'Railway',
    description: 'Technical recruitment for Technician Grade I Signal and Grade III in workshop & loco departments.',
    logoText: 'RRB',
    logoBg: '#FFF7ED',
    logoColor: '#EA580C',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '70+ Mock Tests',
    questionCount: '3200+ Questions',
    pyqYears: '6 Years PYQ',
    isFeatured: false,
    isPopular: false,
    isUpcoming: false,
    expectedDate: 'Notification Active',
    tierInfo: 'CBT Mode Exam + Document Verification',
    eligibility: 'B.Sc / Diploma / ITI in relevant trade',
    subjects: ['General Science', 'Mathematics', 'Reasoning', 'Technical Trade Knowledge'],
    keywords: 'rrb technician grade 1 grade 3 signal workshop iti trade',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'rpf-constable',
    name: 'RPF Constable',
    fullTitle: 'Railway Protection Force - Constable Recruitment',
    category: 'Railway',
    description: 'Recruitment for Constable in Railway Protection Force and Railway Protection Special Force.',
    logoText: 'RPF',
    logoBg: '#FFF7ED',
    logoColor: '#EA580C',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '80+ Mock Tests',
    questionCount: '3500+ Questions',
    pyqYears: '8 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Exam Cycle Active',
    tierInfo: 'CBT, PET/PST & Document Verification',
    eligibility: '10th Class pass from recognized Board',
    subjects: ['General Awareness', 'Arithmetic', 'General Intelligence & Reasoning'],
    keywords: 'rpf constable railway protection force rpsf 10th pass pet pst',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'rpf-si',
    name: 'RPF Sub Inspector',
    fullTitle: 'Railway Protection Force - Sub Inspector',
    category: 'Railway',
    description: 'Recruitment for Sub Inspector in Railway Protection Force across Indian Railways.',
    logoText: 'RPF',
    logoBg: '#FFF7ED',
    logoColor: '#EA580C',
    statusBadgeText: 'ACTIVE',
    badgeClass: 'badge-free',
    mockTestCount: '65+ Mock Tests',
    questionCount: '3000+ Questions',
    pyqYears: '8 Years PYQ',
    isFeatured: false,
    isPopular: false,
    isUpcoming: false,
    expectedDate: 'Exam Cycle Active',
    tierInfo: 'CBT, PET/PST & Document Verification',
    eligibility: 'Graduate in any discipline',
    subjects: ['General Awareness', 'Arithmetic', 'General Intelligence & Reasoning'],
    keywords: 'rpf si sub inspector railway protection force rpsf graduate pet',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },

  // ==================== STATE PSC & BIHAR EXAMS ====================
  {
    id: 'bpsc-cce',
    name: 'BPSC CCE',
    fullTitle: 'Bihar Public Service Commission - Combined Competitive Examination',
    category: 'State PSC',
    description: 'State civil services recruitment exam for Deputy Collector, DSP, Revenue Officer in Bihar Government.',
    logoText: 'BPSC',
    logoBg: '#F0FDF4',
    logoColor: '#15803D',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '100+ Mock Tests',
    questionCount: '4500+ Questions',
    pyqYears: '15 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Date Announced',
    tierInfo: 'Prelims (GS), Mains (GS I, II, Essay & Optional) & Interview',
    eligibility: 'Graduation degree from recognized University',
    subjects: ['General Studies', 'Bihar Special GK', 'Current Affairs', 'History & Geography of Bihar', 'Mental Ability'],
    keywords: 'bpsc bihar state psc deputy collector dsp prelims mains bihar gk history geography',
    mockTestsList: [
      { id: 'bpsc-m1', title: 'BPSC CCE Prelims Full Length Mock 01', duration: '120 Mins', questions: 150, marks: 150, status: 'Free' },
      { id: 'bpsc-m2', title: 'BPSC CCE Prelims Full Length Mock 02', duration: '120 Mins', questions: 150, marks: 150, status: 'Free' }
    ],
    practiceSets: [
      { id: 'bpsc-p1', subject: 'Bihar Special GK', topic: 'Modern History of Bihar & Freedom Movement', qCount: 30, duration: '20 Mins' }
    ],
    pyqList: [
      { id: 'bpsc-pyq-1', year: '2024', title: '70th BPSC CCE Prelims Official Question Paper', duration: '120 Mins', questions: 150 }
    ],
    studyNotes: [
      { id: 'bpsc-n1', title: 'Complete Bihar Special GK & Census 2011 Master Guide', pages: '65 Pages', format: 'PDF' }
    ],
    currentAffairsList: []
  },
  {
    id: 'bihar-police-si',
    name: 'Bihar Police SI',
    fullTitle: 'Bihar Police Subordinate Services Commission - Sub Inspector',
    category: 'Police',
    description: 'Selection for Sub Inspector and Sergeant posts in Bihar Police Department.',
    logoText: 'BP',
    logoBg: '#EFF6FF',
    logoColor: '#1D4ED8',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '85+ Mock Tests',
    questionCount: '3800+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Expected Late 2026',
    tierInfo: 'Prelims, Mains & Physical Efficiency Test (PET)',
    eligibility: 'Graduation + Physical Standard Requirements',
    subjects: ['General Knowledge', 'Current Events', 'Hindi', 'General Studies', 'Mathematics'],
    keywords: 'bihar police si sub inspector sergeant prelims mains pet physical test bpssc',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'bihar-police-constable',
    name: 'Bihar Police Constable',
    fullTitle: 'Central Selection Board of Constable (CSBC) - Bihar Police Constable',
    category: 'Police',
    description: 'Mass recruitment exam for Constable in Bihar Police and Special Armed Police.',
    logoText: 'CSBC',
    logoBg: '#EFF6FF',
    logoColor: '#1D4ED8',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '90+ Mock Tests',
    questionCount: '4000+ Questions',
    pyqYears: '8 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Exam Cycle Active',
    tierInfo: 'Written Examination & PET (Physical Test)',
    eligibility: '10+2 (Intermediate) pass',
    subjects: ['Hindi', 'English', 'Mathematics', 'Social Science', 'Science', 'General Knowledge'],
    keywords: 'bihar police constable csbc 12th pass physical pet hindi gk math science',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'bihar-ssc-cgl',
    name: 'Bihar SSC CGL',
    fullTitle: 'Bihar Staff Selection Commission - Combined Graduate Level',
    category: 'State Government Jobs',
    description: 'Recruitment for Secretariat Assistant, Planning Assistant, and Auditor posts in Bihar Government.',
    logoText: 'BSSC',
    logoBg: '#F0FDF4',
    logoColor: '#15803D',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '80+ Mock Tests',
    questionCount: '3600+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Expected Late 2026',
    tierInfo: 'Prelims & Mains CBT Examination',
    eligibility: 'Bachelor Degree in any discipline',
    subjects: ['General Studies', 'General Science & Mathematics', 'Comprehension / Logic / Mental Ability'],
    keywords: 'bssc cgl bihar staff selection secretariat assistant prelims mains',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'bihar-teacher-tre',
    name: 'Bihar Teacher (BPSC TRE)',
    fullTitle: 'Bihar Public Service Commission - Teacher Recruitment Exam',
    category: 'Teaching',
    description: 'State recruitment examination for Primary (1-5), Middle (6-8), Secondary (9-10) and Senior Secondary (11-12) teachers.',
    logoText: 'TRE',
    logoBg: '#FAF5FF',
    logoColor: '#7E22CE',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '110+ Mock Tests',
    questionCount: '4800+ Questions',
    pyqYears: '5 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Annual Examination',
    tierInfo: 'Written Test (Language qualifying + General Studies & Subject)',
    eligibility: 'D.El.Ed / B.Ed / STET / CTET Qualified',
    subjects: ['Language (Hindi/English)', 'General Studies', 'Subject Specialization'],
    keywords: 'bihar teacher tre bpsc primary middle secondary stet ctet teaching',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'uppsc-pcs',
    name: 'UPPSC PCS',
    fullTitle: 'Uttar Pradesh Public Service Commission - Combined State Service Exam',
    category: 'State PSC',
    description: 'State civil service examination for SDM, DSP, Commercial Tax Officer in Uttar Pradesh.',
    logoText: 'UP',
    logoBg: '#F0FDF4',
    logoColor: '#166534',
    statusBadgeText: 'UPCOMING',
    badgeClass: 'badge-upcoming',
    mockTestCount: '90+ Mock Tests',
    questionCount: '4000+ Questions',
    pyqYears: '12 Years PYQ',
    isFeatured: false,
    isPopular: false,
    isUpcoming: true,
    expectedDate: 'Expected Nov 2026',
    tierInfo: 'Prelims, Mains (GS Papers I-VI) & Interview',
    eligibility: 'Bachelor Degree in any discipline',
    subjects: ['General Studies I', 'CSAT', 'UP Special GS', 'Essay'],
    keywords: 'uppsc pcs uttar pradesh sdm dsp prelims mains up special',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },

  // ==================== UPSC EXAMS ====================
  {
    id: 'upsc-cse',
    name: 'UPSC Civil Services',
    fullTitle: 'Union Public Service Commission - Civil Services Examination',
    category: 'UPSC',
    description: 'India premier administrative recruitment exam for IAS, IPS, IFS, IRS, and allied Group A Services.',
    logoText: 'UPSC',
    logoBg: '#FEF2F2',
    logoColor: '#DC2626',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '140+ GS & CSAT Tests',
    questionCount: '6000+ Questions',
    pyqYears: '20 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Annual Cycle',
    tierInfo: 'Prelims (GS + CSAT), Mains (9 Papers) & Personality Test',
    eligibility: 'Degree from recognized university (Min Age 21)',
    subjects: ['General Studies I', 'CSAT (GS Paper II)', 'Essay', 'Polity & Governance', 'History & Culture', 'Economy & Environment'],
    keywords: 'upsc cse ias ips ifs civil services prelims mains csat polity history geography economy',
    mockTestsList: [
      { id: 'upsc-m1', title: 'UPSC CSE Prelims GS Paper-1 Mock 01', duration: '120 Mins', questions: 100, marks: 200, status: 'Free' },
      { id: 'upsc-m2', title: 'UPSC CSE Prelims CSAT Paper-2 Mock 01', duration: '120 Mins', questions: 80, marks: 200, status: 'Free' }
    ],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'upsc-nda',
    name: 'UPSC NDA',
    fullTitle: 'Union Public Service Commission - National Defence Academy',
    category: 'UPSC',
    description: 'Admission into Army, Navy, and Air Force wings of NDA and Indian Naval Academy Course (INAC).',
    logoText: 'NDA',
    logoBg: '#FEF3C7',
    logoColor: '#D97706',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '85+ Mock Tests',
    questionCount: '3500+ Questions',
    pyqYears: '15 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Bi-Annual Examination',
    tierInfo: 'Written Exam (Mathematics & GAT) & SSB Interview',
    eligibility: '10+2 Pass (Physics & Maths required for Navy/Air Force)',
    subjects: ['Mathematics', 'General Ability Test (English, Physics, Chemistry, GK)'],
    keywords: 'upsc nda defence army navy air force ssb interview math gat 12th pass',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'upsc-cds',
    name: 'UPSC CDS',
    fullTitle: 'Union Public Service Commission - Combined Defence Services',
    category: 'UPSC',
    description: 'Recruitment into Indian Military Academy (IMA), Naval Academy, Air Force Academy, and Officers Training Academy (OTA).',
    logoText: 'CDS',
    logoBg: '#FEF3C7',
    logoColor: '#B45309',
    statusBadgeText: 'UPCOMING',
    badgeClass: 'badge-upcoming',
    mockTestCount: '80+ Mock Tests',
    questionCount: '3200+ Questions',
    pyqYears: '14 Years PYQ',
    isFeatured: false,
    isPopular: false,
    isUpcoming: true,
    expectedDate: 'Expected Nov 2026',
    tierInfo: 'Written Examination & SSB Interview',
    eligibility: 'Degree from recognized University / Engineering for AFA',
    subjects: ['English', 'General Knowledge', 'Elementary Mathematics'],
    keywords: 'upsc cds defence ima ota afa ssb military army officer graduate',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },

  // ==================== POLICE & DEFENCE EXAMS ====================
  {
    id: 'up-police-constable',
    name: 'UP Police Constable',
    fullTitle: 'Uttar Pradesh Police Recruitment and Promotion Board - Constable',
    category: 'Police',
    description: 'Mass recruitment exam for Civil Police Constable and Pradeshik Armed Constabulary (PAC) in UP.',
    logoText: 'UPP',
    logoBg: '#EFF6FF',
    logoColor: '#1D4ED8',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '105+ Mock Tests',
    questionCount: '4200+ Questions',
    pyqYears: '8 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Cycle Active',
    tierInfo: 'Written Examination, DV/PST & PET',
    eligibility: '10+2 (Intermediate) Pass',
    subjects: ['General Knowledge', 'General Hindi', 'Numerical & Mental Ability', 'Mental Aptitude / Reasoning'],
    keywords: 'up police constable upprb pac 12th pass hindi gk reasoning physical',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'afcat',
    name: 'AFCAT',
    fullTitle: 'Air Force Common Admission Test - Flying & Ground Duty',
    category: 'Defence',
    description: 'Commissioned Officer recruitment exam for Flying Branch and Ground Duty (Technical & Non-Technical) in IAF.',
    logoText: 'IAF',
    logoBg: '#FEF3C7',
    logoColor: '#D97706',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '65+ Mock Tests',
    questionCount: '2600+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Bi-Annual Exam',
    tierInfo: 'Online Examination & AFSB Interview',
    eligibility: 'Graduation / B.Tech with required physical & medical standards',
    subjects: ['Verbal Ability in English', 'Numerical Ability', 'Reasoning & Military Aptitude', 'General Awareness'],
    keywords: 'afcat air force officer flying ground duty afsb interview English reasoning',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },

  // ==================== TEACHING EXAMS ====================
  {
    id: 'ctet',
    name: 'CTET',
    fullTitle: 'Central Teacher Eligibility Test (Central Board of Secondary Education)',
    category: 'Teaching',
    description: 'National level eligibility certificate for teaching in Kendriya Vidyalayas (KVS), Navodayas (NVS) & Central schools.',
    logoText: 'CTET',
    logoBg: '#FAF5FF',
    logoColor: '#7E22CE',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '120+ Mock Tests',
    questionCount: '5000+ Questions',
    pyqYears: '12 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Bi-Annual Examination',
    tierInfo: 'Paper 1 (Class 1-5) & Paper 2 (Class 6-8)',
    eligibility: 'D.El.Ed / B.Ed / D.Ed with minimum qualifying marks',
    subjects: ['Child Development & Pedagogy', 'Language I', 'Language II', 'Mathematics', 'EVS / Social Science'],
    keywords: 'ctet teaching cbse central teacher eligibility paper 1 paper 2 pedagogy evs',
    mockTestsList: [
      { id: 'ctet-m1', title: 'CTET Paper-1 Primary Full Mock 01', duration: '150 Mins', questions: 150, marks: 150, status: 'Free' }
    ],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'ugc-net',
    name: 'UGC NET',
    fullTitle: 'National Eligibility Test for Assistant Professor & JRF (NTA)',
    category: 'Teaching',
    description: 'Qualifying exam for Assistant Professor award and Junior Research Fellowship (JRF) in Indian Universities.',
    logoText: 'NET',
    logoBg: '#FAF5FF',
    logoColor: '#6B21A8',
    statusBadgeText: 'UPCOMING',
    badgeClass: 'badge-upcoming',
    mockTestCount: '100+ Mock Tests',
    questionCount: '4000+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: true,
    expectedDate: 'Expected Dec 2026',
    tierInfo: 'Paper 1 (Teaching & Research) & Paper 2 (Subject)',
    eligibility: 'Master Degree with minimum 55% marks',
    subjects: ['Teaching & Research Aptitude', 'Higher Education System', 'Information & Communication Tech (ICT)', 'Subject Specialization'],
    keywords: 'ugc net nta assistant professor jrf research aptitude paper 1 paper 2',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },

  // ==================== MEDICAL & ENGINEERING EXAMS ====================
  {
    id: 'neet-ug',
    name: 'NEET UG',
    fullTitle: 'National Eligibility cum Entrance Test (Undergraduate)',
    category: 'Medical',
    description: 'Single national entrance exam for admission to MBBS, BDS, BAMS, BHMS & AYUSH medical courses.',
    logoText: 'NEET',
    logoBg: '#ECFDF5',
    logoColor: '#059669',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '160+ Chapter & Full Tests',
    questionCount: '7000+ Questions',
    pyqYears: '15 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Annual Examination',
    tierInfo: 'Pen & Paper Test (OMR Sheet)',
    eligibility: '10+2 with Physics, Chemistry, Biology/Biotechnology',
    subjects: ['Botany', 'Zoology', 'Physics', 'Chemistry'],
    keywords: 'neet ug medical mbbs bds biology physics chemistry nta omr',
    mockTestsList: [
      { id: 'neet-m1', title: 'NEET UG Full Length Mock Test 01', duration: '200 Mins', questions: 200, marks: 720, status: 'Free' }
    ],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'jee-main',
    name: 'JEE Main',
    fullTitle: 'Joint Entrance Examination Main (National Testing Agency)',
    category: 'Engineering',
    description: 'National level engineering entrance exam for admission into NITs, IIITs, CFTIs, and qualifying for JEE Advanced.',
    logoText: 'JEE',
    logoBg: '#EFF6FF',
    logoColor: '#2563EB',
    statusBadgeText: 'FEATURED',
    badgeClass: 'badge-live',
    mockTestCount: '180+ Chapter & Full Tests',
    questionCount: '8000+ Questions',
    pyqYears: '15 Years PYQ',
    isFeatured: true,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Session 1 & 2 Annual',
    tierInfo: 'Computer Based Test (Physics, Chemistry, Maths)',
    eligibility: '10+2 Pass/Appearing with Physics, Chemistry & Mathematics',
    subjects: ['Physics', 'Chemistry', 'Mathematics'],
    keywords: 'jee main engineering entrance iit nit iiit physics chemistry math nta',
    mockTestsList: [
      { id: 'jee-m1', title: 'JEE Main Full Length Mock Test 01', duration: '180 Mins', questions: 90, marks: 300, status: 'Free' }
    ],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'gate-cs',
    name: 'GATE CS & IT',
    fullTitle: 'Graduate Aptitude Test in Engineering - Computer Science',
    category: 'Engineering',
    description: 'National examination for M.Tech admissions in IITs/NITs and PSU recruitment (IOCL, NTPC, ONGC).',
    logoText: 'GATE',
    logoBg: '#F0F9FF',
    logoColor: '#0369A1',
    statusBadgeText: 'UPCOMING',
    badgeClass: 'badge-upcoming',
    mockTestCount: '95+ Subject & Full Mocks',
    questionCount: '3800+ Questions',
    pyqYears: '15 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: true,
    expectedDate: 'Expected Feb 2027',
    tierInfo: 'Computer Based Test (65 Questions / 100 Marks)',
    eligibility: 'Bachelor degree in Engineering / Technology or Master in relevant Science subject',
    subjects: ['General Aptitude', 'Engineering Mathematics', 'Computer Science Core (Algorithms, OS, DBMS, Networks)'],
    keywords: 'gate cs it engineering mtech psu computer science algorithms os dbms',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },

  // ==================== LAW, INSURANCE, MBA, CUET ====================
  {
    id: 'clat-ug',
    name: 'CLAT UG',
    fullTitle: 'Common Law Admission Test (Consortium of National Law Universities)',
    category: 'Law',
    description: 'National level entrance examination for 5-year integrated LL.B. degree programs in NLUs.',
    logoText: 'CLAT',
    logoBg: '#FEFCE8',
    logoColor: '#A16207',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '75+ Full Length Mocks',
    questionCount: '3000+ Questions',
    pyqYears: '10 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Expected Dec 2026',
    tierInfo: 'Off-line Pen & Paper Passage-based Test',
    eligibility: '10+2 or equivalent with minimum 45% marks',
    subjects: ['English Language', 'Current Affairs & GK', 'Legal Reasoning', 'Logical Reasoning', 'Quantitative Techniques'],
    keywords: 'clat nlu law entrance llb legal reasoning passage based',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'lic-aao',
    name: 'LIC AAO',
    fullTitle: 'Life Insurance Corporation - Assistant Administrative Officer',
    category: 'Insurance',
    description: 'Officer cadre recruitment in Life Insurance Corporation of India.',
    logoText: 'LIC',
    logoBg: '#F0FDF4',
    logoColor: '#166534',
    statusBadgeText: 'UPCOMING',
    badgeClass: 'badge-upcoming',
    mockTestCount: '70+ Mock Tests',
    questionCount: '2800+ Questions',
    pyqYears: '8 Years PYQ',
    isFeatured: false,
    isPopular: false,
    isUpcoming: true,
    expectedDate: 'Expected Late 2026',
    tierInfo: 'Prelims, Mains & Interview',
    eligibility: 'Bachelor degree in any discipline',
    subjects: ['Reasoning Ability', 'Quantitative Aptitude', 'English Language', 'General Knowledge', 'Insurance & Financial Market Awareness'],
    keywords: 'lic aao insurance assistant administrative officer financial awareness',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'cat',
    name: 'CAT',
    fullTitle: 'Common Admission Test (Indian Institutes of Management)',
    category: 'MBA',
    description: 'Premier national management entrance exam for admission into IIMs and top B-Schools in India.',
    logoText: 'CAT',
    logoBg: '#FDF4FF',
    logoColor: '#A21CAF',
    statusBadgeText: 'UPCOMING',
    badgeClass: 'badge-upcoming',
    mockTestCount: '85+ Full Mocks',
    questionCount: '3200+ Questions',
    pyqYears: '15 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: true,
    expectedDate: 'Expected Nov 2026',
    tierInfo: 'Computer Based Test (VARC, DILR, QA)',
    eligibility: 'Bachelor Degree with minimum 50% marks',
    subjects: ['Verbal Ability & Reading Comprehension', 'Data Interpretation & Logical Reasoning', 'Quantitative Ability'],
    keywords: 'cat iim mba management b school varc dilr quant aptitude',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  },
  {
    id: 'cuet-ug',
    name: 'CUET UG',
    fullTitle: 'Common University Entrance Test - Undergraduate',
    category: 'CUET',
    description: 'Single window entrance test for admission to undergraduate programs in Central Universities.',
    logoText: 'CUET',
    logoBg: '#FFF1F2',
    logoColor: '#E11D48',
    statusBadgeText: 'POPULAR',
    badgeClass: 'badge-free',
    mockTestCount: '120+ Domain Tests',
    questionCount: '4500+ Questions',
    pyqYears: '4 Years PYQ',
    isFeatured: false,
    isPopular: true,
    isUpcoming: false,
    expectedDate: 'Annual Cycle',
    tierInfo: 'CBT (Language, Domain Subjects & General Test)',
    eligibility: 'Class 12 Pass or appearing from recognized board',
    subjects: ['Language Section', 'Domain Specific Subjects', 'General Test'],
    keywords: 'cuet ug central university admissions du jnu bhu domain test ncert',
    mockTestsList: [],
    practiceSets: [],
    pyqList: [],
    studyNotes: [],
    currentAffairsList: []
  }
];

/**
 * Data Access Helpers
 */
export function getAllExams() {
  return EXAMS_DATA;
}

export function getExamById(id) {
  return EXAMS_DATA.find(e => e.id === id) || null;
}

export function filterExams(category = 'All', searchQuery = '') {
  const query = (searchQuery || '').trim().toLowerCase();

  return EXAMS_DATA.filter(exam => {
    // Category match
    let matchesCategory = true;
    if (category === 'Popular') {
      matchesCategory = exam.isPopular === true;
    } else if (category === 'State Exams') {
      matchesCategory = exam.category === 'State PSC' || exam.category === 'State Government Jobs' || exam.id.startsWith('bihar-');
    } else if (category !== 'All') {
      matchesCategory = exam.category.toLowerCase() === category.toLowerCase();
    }

    // Search query match
    let matchesSearch = true;
    if (query) {
      const searchableText = `${exam.name} ${exam.fullTitle} ${exam.category} ${exam.description} ${exam.keywords}`.toLowerCase();
      matchesSearch = searchableText.includes(query);
    }

    return matchesCategory && matchesSearch;
  });
}

export function getFeaturedExams() {
  return EXAMS_DATA.filter(e => e.isFeatured);
}

export function getPopularExams() {
  return EXAMS_DATA.filter(e => e.isPopular);
}

export function getUpcomingExams() {
  return EXAMS_DATA.filter(e => e.isUpcoming);
}
